### ISSUE TITLE
[BUG]: CSM Authorization - Karavictl cli not giving prompt for password 

### ISSUE THREAD

**Issue by gloriousbao** [dell/csm#1349] opened 2024-06-27 15:22 UTC
### Bug Description

karavictl storage create doesnt prompt for password when not passing --password, it ends up trying to authenticate with empty password

Command used and output below 

```
./karavictl storage create --array-insecure --insecure --addr xxxxxx:443 --type powermax --endpoint https://xxxxxxxxx --user test --admin-token admin.yaml
{
  "ErrorMsg": "rpc error: code = Unknown desc = powermax authentication failed: Unauthorized"
}
```

### Logs

time="2024-06-27T15:18:54Z" level=error msg="creating storage: rpc error: code = Unknown desc = powermax authentication failed: Unauthorized" error="rpc error: code = Unknown desc = powermax authentication failed: Unauthorized"
time="2024-06-27T15:18:54Z" level=error msg="rpc error: code = Unknown desc = powermax authentication failed: Unauthorized

### Steps to Reproduce

Run karavictl storage create command

### Expected Behavior

Should ask for password via stdin and hide it for others 

### CSM Driver(s)

CSM Authorization 1.9.1
CSM Powermax 2.9.1 

### Container Orchestrator

Openshift

### Operating System

CORE OS

**Comment by atye** [comment] 2024-06-27 15:36
Duplicate of https://github.com/dell/csm/issues/1347.

We can keep this open until @coulof has verified the fix with you.

**Comment by gallacher** [comment] 2024-06-28 10:56
Closing this as we do not want duplicate issues open.  Thanks.

**Closed by gallacher** 2024-06-28 10:56 UTC
Labels: type/bug, area/csm-authorization
