### ISSUE TITLE
[QUESTION]:How to gather Powerstore latest metrics every 10 sec using karavi-observability?

### ISSUE THREAD

**Issue by hiroo-kitamura** [dell/csm#1021] opened 2023-10-26 07:55 UTC
### How can the Team help you today?

**Details: ?**

I installed karavi-observability on OpenShift and set it up to gather Powerstore Metrics.
karavi-observability gathers metrics every 10 seconds, but the same values are gathered for 300 seconds from Powerstore. 

- Questions
  - Is it possible to change the frequency of generating metrics by Powerstore?
    - If it's possible, how can I change it?
    - If it's **NOT** possible, are there any solutions with this problem? 

- karavi-observability settings (karavi-metrics-powerstore-configmap)
  - Polling frequency to the PowerStore is 10 seconds.
```
    COLLECTOR_ADDR: otel-collector:55680
    PROVISIONER_NAMES: csi-powerstore.dellemc.com
    POWERSTORE_VOLUME_IO_POLL_FREQUENCY: "10"
    POWERSTORE_VOLUME_METRICS_ENABLED: "true"
    POWERSTORE_MAX_CONCURRENT_QUERIES: "10"
    POWERSTORE_SPACE_POLL_FREQUENCY: "10"
    POWERSTORE_ARRAY_POLL_FREQUENCY: "10"
    POWERSTORE_FILE_SYSTEM_POLL_FREQUENCY: "10"
    LOG_LEVEL: "INFO"
    LOG_FORMAT: "text"
    ZIPKIN_URI: "http://<zipkin addr>:9411/api/v2/spans"
    ZIPKIN_SERVICE_NAME: "metrics-powerstore"
    ZIPKIN_PROBABILITY: "1.0"
```
- Debug using zipkin dashboard
  - karavi-observability seems to send a request to Powerstore every 10 seconds.

[Environment]
- Openshift (Container Platform) v4.12
- Powerstore 1200T
- CSI Driver v2.7.0
- karavi-observability (CSM for Observability) v1.5.0

**Comment by donatwork** [comment] 2023-10-26 10:36
It is not advisable to reduce the interval for PowerStore metrics for two reasons. The first is that doing so will put more load on the storage array and the second is that the metrics collection interval in PowerStore is longer than ten seconds so a shorter interval will not return new metrics. I don't have the number in mind at the moment but it is in minutes and not seconds.

**Comment by hiroo-kitamura** [comment] 2023-10-27 04:42
@donatwork 
Thank you for the helpful advice, I understand that it's not recommended to set the interval too short.
Then, I would like to set the interval shorter than 300 seconds even just a little (e.g. set to 180 seconds), so could you tell me how to change metrics collection interval in PowerStore.

**Comment by donatwork** [comment] 2023-10-27 14:44
If you login to the PowerStore array and look at the online help you will see a section on metrics collection. All user settings are documented in that online help. 

You can change the metrics collection on a per object basis from the PowerStore UI under the **Actions** sub menu. "Change Metric Granularity". I recommend that you work PowerStore support to determine what is optimal for your use case.

**Comment by hiroo-kitamura** [comment] 2023-10-30 03:00
@donatwork 
Thank you, I understood that how to change performance metrics collection interval setting in PowerStore.
However, the setting which I'd like to change are capacity metrics collection interval.
It seems impossible to change from the PowerStore UI.

I suppose that the following setting `storageCapacity.pollInterval` of CSI driver could change, but is it correct?
If it's not correct, could you tell me how to change the capacity metrics collection interval.

```
# Storage Capacity Tracking
# Note: Capacity tracking is supported in kubernetes v1.24 and above, this feature will be automatically disabled in older versions.
storageCapacity:
  # enabled : Enable/Disable storage capacity tracking
  # Allowed values:
  #   true: enable storage capacity tracking
  #   false: disable storage capacity tracking
  # Default value: true
  enabled: true
  # pollInterval : Configure how often external-provisioner polls the driver to detect changed capacity
  # Allowed values: 1m,2m,3m,...,10m,...,60m etc
  # Default value: 5m
  pollInterval: 5m
```

* Reference: https://dell.github.io/csm-docs/v1/csidriver/features/powerstore/#storage-capacity-tracking

**Comment by donatwork** [comment] 2023-11-01 12:45
The metrics interval for the array is not done at an array level. It is calculated from the free space per volume/filesystem and summed up. There is no public setting at the PowerStore level. 

To get the volume metrics we use the POST method to metrics/generate, see https://<your array address>/swaggerui/#/metrics/post_metrics_generate. The current Observability code has lowest granularity of 20 seconds. In PowerStore 3.0.0.0 there is a five second interval but the current Observability code has a 20s interval at the smallest interval. Some code changes will be needed in Observability to go lower.

**Comment by hiroo-kitamura** [comment] 2023-11-02 05:42
@donatwork Thank you for the answer.

> The metrics interval for the array is not done at an array level. It is calculated from the free space per volume/filesystem and summed up. There is no public setting at the PowerStore level.

Regarding the above comment, I've already successfully collected volume metrics using karavi-observability.
Therefore, there seems to be no need to use the additional POST method `post_metrics_generate`.

**I would like to re-explain the issue I would like to solve.**

![architecture](https://dell.github.io/csm-docs/docs/observability/obs_architecture1.png)
<https://dell.github.io/csm-docs/docs/observability/design/#default-deployment-of-csm-for-observability>

I've built an environment following the above architecture.
The below is my situation.

- Success
  - Each pod included in `Namespace: karavi-observability` is able to gather data at the expected frequency
- Failure
  - The same values are gathered for 300 seconds from Powerstore
- Solution
  - Update the CSI driver setting `storageCapacity.pollInterval` from 5m(default) to 3m

Could you comment the above `Solution` is appropriate or not.

**Comment by hiroo-kitamura** [comment] 2023-11-02 08:18
> Solution
> * Update the CSI driver setting `storageCapacity.pollInterval` from 5m(default) to 3m

I tried the above `Solution`, but unfortunately the issue wasn't solved.
If there are any other ways to solve the following issues, could you suggest them.
- The same values are gathered for 300 seconds from Powerstore

**Comment by donatwork** [comment] 2023-11-02 11:57
The driver setting storageCapacity.pollInterval is not used by the Observability module. It is used for driver functionality when managing volumes as documented in the comment for that setting.

**Comment by donatwork** [comment] 2023-11-02 12:35
@hiroo-kitamura Are you saying that the issue is that the **driver** is not honoring storageCapacity.pollInterval value?

**Comment by hiroo-kitamura** [comment] 2023-11-06 04:35
@donatwork Thank you for your reply.
I'm so sorry, but there is a misinterpretation, so I would like to correct it.

> The driver setting storageCapacity.pollInterval is not used by the Observability module. It is used for driver functionality when managing volumes as documented in the comment for that setting.

Thank you, I understand.

> Are you saying that the issue is that the driver is not honoring storageCapacity.pollInterval value? I'm now interpreting "from PowerStore" to mean the CSI PowerStore driver and not the array itself. Am I correct?

No, It's not correct.

What I would like to accomplish is the following.
- In karavi-observability, I would like to gather metrics generated from PowerStore at a cycle shorter than 5 minutes via PowerStore API.
- **NOTE: Let me emphasize that this is the PowerStore metrics generation cycle, not the gathering cycle.**

If there is a way to achieve the above, please let me know.

**Comment by donatwork** [comment] 2023-11-10 06:47
OK I believe that I understand the problem now. Observability is requesting the metrics according to the set interval but the data returned is updated every five minutes. The behavior in PowerStore is something that needs to be investigated with PowerStore support as the version of PowerStore array software may impact the refresh interval.

**Comment by hiroo-kitamura** [comment] 2023-11-13 06:51
Thanks for your support.
I will contact to the PowerStore support.

**Comment by donatwork** [comment] 2023-11-14 07:57
Closing issue as the questions have been answered.

**Closed by donatwork** 2023-11-14 07:57 UTC
Labels: type/question, area/csm-observability
