### ISSUE TITLE
[BUG]: PowerStore CSI blockProtocol:auto assumes NVMe when configured for iSCSI

### ISSUE THREAD

**Issue by DougBernhardt** [dell/csm#1125] opened 2024-01-31 22:37 UTC
### Bug Description

in the powerstore-config secret,when the default of "auto" is used in iSCSI environment for blockProtocol, it incorrectly configured for NVMe and therefore volumes would not mount. Changing blockProtocol to "ISCSI" allows them to successfully mount.

### Logs

  Warning  FailedMount             15s (x6 over 31s)  kubelet                  MountVolume.MountDevice failed for volume "csivol-d9b7b3988b" : rpc error: code = InvalidArgument desc = NVMeTCP Targets data must be in publish context
  Warning  FailedMount             6s                 kubelet                  Unable to attach or mount volumes: unmounted volumes=[mssqldb mssqldata mssqllog], unattached volumes=[kube-api-access-ht66c mssqldb mssqldata mssqllog]: timed out waiting for the condition
  Warning  FailedMount             0s (x7 over 32s)   kubelet                  MountVolume.MountDevice failed for volume "csivol-c660fc6d1e" : rpc error: code = InvalidArgument desc = NVMeTCP Targets data must be in publish context
  Warning  FailedMount             0s (x7 over 32s)   kubelet                  MountVolume.MountDevice failed for volume "csivol-b12213bad8" : rpc error: code = InvalidArgument desc = NVMeTCP Targets data must be in publish context

### Steps to Reproduce

 Hosts are configured for iSCSI, deploy PowerStore CSI using default values for blockProtocol.

### Expected Behavior

Should detect iSCSI being used and mount volumes

### CSM Driver(s)

CSI Driver for PowerStore 2.9.0

### Installation Type

Helm via Rancher catalog

### Container Orchestrator

v1.26.11+rke2r1

### Operating System

openSUSE Leap 15.5

**Comment by jasonboche** [comment] 2024-01-31 23:03
Thank you for writing this up Doug.

**Comment by delldubey** [comment] 2024-02-01 05:53
Hi @DougBernhardt,
Please share the Node driver log here.
Thanks

**Comment by DougBernhardt** [comment] 2024-02-01 18:54
Here is the host registered in PowerStore incorrectly under NVMe and node driver log file:
![image](https://github.com/dell/csm/assets/39528722/6318c5bd-b3d0-435c-b8bb-41582fac2353)
[powerstore-node-zbk7m_driver.log](https://github.com/dell/csm/files/14129605/powerstore-node-zbk7m_driver.log)

**Comment by delldubey** [comment] 2024-02-12 11:27
@DougBernhardt ,
Based on the logs I see there are NVME Inititators present on the host with iSCSI initiators:
NVME:
```
{"level":"info","msg":"initiator name is: [nqn.2014-08.org.nvmexpress:uuid:d4d81742-fd2f-ad34-5a25-a48fd39840ac]","time":"2024-02-01T18:43:48.474963369Z"}
{"level":"debug","msg":"NVMe initiators found on node","time":"2024-02-01T18:43:48.474976066Z"}
```
iSCSI:
```
{"level":"info","msg":"initiator name is: [iqn.2016-04.com.open-iscsi:80b9d804a15]","time":"2024-02-01T18:43:48.474833972Z"}
{"level":"debug","msg":"iscsi initiators found on node","time":"2024-02-01T18:43:48.474846274Z"}
```
Based on the working of **auto**  as mentioned here:
https://dell.github.io/csm-docs/v3/csidriver/features/powerstore/#nvme-support, 
it will take NVME protocol in precedence.

**Comment by DougBernhardt** [comment] 2024-02-12 19:43
Unfortunately, the NVMe initiators must be present by default. I did not configure them.  This was a base SUSE install with only iSCSI enabled and configured via YAST. I think the precedence order should be different or perhaps do not default to "auto" and force the user to make a selection unless "auto" can be modified to perform additional checks. That way they are aware of what block mode is being used other than relying on "auto" to detect it correctly. If the user does not know what block mode they are using, they will probably have challenges trying to troubleshoot why volumes will not mount.

**Comment by AkshaySainiDell** [comment] 2024-03-08 05:16
Thanks @DougBernhardt we will consider this in future roadmap.
Closing the issue as root cause was NVMe initiators present on the cluster and not a bug in the driver.

**Closed by AkshaySainiDell** 2024-03-08 05:16 UTC
Labels: needs-triage, type/bug
