### ISSUE TITLE
[FEATURE]: Update drivers to use 1.4.0 Authorization sidecar

### ISSUE THREAD

**Issue by bjiang27** [dell/csm#448] opened 2022-08-26 16:41 UTC
**Describe the solution you'd like**
Update Authorization sidecar to latest 1.4.0 image

**Comment by shaynafinocchiaro** [comment] 2022-08-29 19:23
Duplicate of https://github.com/dell/csm/issues/350

**Closed by shaynafinocchiaro** 2022-08-29 19:23 UTC
Labels: type/feature, area/csm-authorization, area/csi-powerflex, area/csi-powerscale, area/csi-powermax, backlog
