### ISSUE TITLE
[QUESTION]: "CrashLoopBackOff" occurs when restarting "powerstore-controller" after nodes terminates abnormally

### ISSUE THREAD

**Issue by at-tkimura** [dell/csm#987] opened 2023-09-22 07:14 UTC
### How can the Team help you today?

**Details: ?**

All nodes in the OCP cluster that were running the CSI driver terminated abnormally.
After the node was rebooted, the CSI driver went through the boot process, but the pod status of the `powerstore-controller` was `CrashLoopBackOff`.

*After running the `oc rollout restart deploy/powerstore-controller` command, the pod status of `powerstore-controller` became `running`.

I don't know the cause, so I would like to know how to prevent `CrashLoopBackOff` from occurring.

- powerstore-controller pod log:
```
Defaulted container "attacher" out of: attacher, resizer, provisioner, snapshotter, dell-csi-replicator, csi-metadata-retriever, driver
I0915 08:09:48.168237       1 main.go:96] Version: v4.3.0
I0915 08:09:48.170134       1 connection.go:164] Connecting to unix:///var/run/csi/csi.sock
W0915 08:09:58.170270       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0915 08:10:08.170263       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0915 08:10:18.171212       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0915 08:10:28.171137       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0915 08:10:38.170529       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0915 08:10:48.170640       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0915 08:10:58.170841       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0915 08:11:08.171127       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
...snip...
```

- csi-metadata-retriever container log:
```
time="2023-09-21T05:22:23Z" level=fatal msg="failed to listen" error="listen unix /var/run/csi/csi_retriever.sock: bind: address already in use"
```

- environment:
  - Operating System: RHEL 8.7
  - Container Orchestrator: Openshift 4.12.28
  - CSM Driver(s): CSI Driver for PowerStore v2.7.0
  - Installation Type: Helm Install
  - Model: PowerStore 1200T

Kind regards.

**Comment by adarsh-dell** [comment] 2023-09-22 12:22
Hello @at-tkimura,

Did you have a chance to provide a description of the controller pod and confirm which container was experiencing crashes? Specifically, I'm interested in knowing whether it was the driver or any other sidecars (such as the attacher, etc.). 

Additionally, I would appreciate it if you could share the output of 'kubectl describe powerstore-controller-xyz'.
Please share the complete logs of controller pods.
Thanks

**Comment by at-tkimura** [comment] 2023-09-25 05:05
@adarsh-dell 
Thank you for your reply.

Now that the above machine has recovered, I'll post the logs from another machine that had the same issue.
*The version of "csi-powerstore" is v2.6.0.

```
$ oc describe pod powerstore-controller-65856bff55-rgpq2
Name:             powerstore-controller-65856bff55-rgpq2
Namespace:        xxxnamespacexxx
Priority:         0
Service Account:  powerstore-controller
Node:             xxxnodexxx/xx.xx.xx.xx
Start Time:       Fri, 01 Sep 2023 14:58:05 +0900
Labels:           name=powerstore-controller
                  pod-template-hash=65856bff55
Annotations:      k8s.ovn.org/pod-networks:
                    {"default":{"ip_addresses":["xx.xx.xx.xx/23"],"mac_address":"xx:xx:xx:xx:xx:xx","gateway_ips":["xx.xx.xx.1"],"ip_address":"xx.xx.xx.xx/23","...
                  k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "ovn-kubernetes",
                        "interface": "eth0",
                        "ips": [
                            "xx.xx.xx.xx"
                        ],
                        "mac": "xx:xx:xx:xx:xx:xx",
                        "default": true,
                        "dns": {}
                    }]
                  k8s.v1.cni.cncf.io/networks-status:
                    [{
                        "name": "ovn-kubernetes",
                        "interface": "eth0",
                        "ips": [
                            "xx.xx.xx.xx"
                        ],
                        "mac": "xx:xx:xx:xx:xx:xx",
                        "default": true,
                        "dns": {}
                    }]
                  openshift.io/scc: restricted-v2
                  seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:           Running
IP:               xx.xx.xx.xx
IPs:
  IP:           xx.xx.xx.xx
Controlled By:  ReplicaSet/powerstore-controller-65856bff55
Containers:
  attacher:
    Container ID:  cri-o://92ee1b7c989d3c633498ab5ca4d60ed08c95596bc8ef715e8178a6d6d12c3594
    Image:         k8s.gcr.io/sig-storage/csi-attacher:v4.2.0
    Image ID:      k8s.gcr.io/sig-storage/csi-attacher@sha256:1ec3649e8bd7f968dcca6f3578896a4481962af2fe8e16d1aadf555288fdae36
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=5
      --leader-election
      --worker-threads=130
      --resync=10s
      --timeout=130s
    State:          Running
      Started:      Tue, 19 Sep 2023 10:12:35 +0900
    Ready:          True
    Restart Count:  1
    Environment:
      ADDRESS:  /var/run/csi/csi.sock
    Mounts:
      /var/run/csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gq9zz (ro)
  resizer:
    Container ID:  cri-o://e027493e42647fa703d20492a65728f944153d6fab701b853cbf2240407c7353
    Image:         k8s.gcr.io/sig-storage/csi-resizer:v1.7.0
    Image ID:      k8s.gcr.io/sig-storage/csi-resizer@sha256:3a7bdf5d105783d05d0962fa06ca53032b01694556e633f27366201c2881e01d
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=5
      --leader-election
    State:          Running
      Started:      Tue, 19 Sep 2023 10:13:30 +0900
    Ready:          True
    Restart Count:  1
    Environment:
      ADDRESS:  /var/run/csi/csi.sock
    Mounts:
      /var/run/csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gq9zz (ro)
  provisioner:
    Container ID:  cri-o://1a1fb72948ac19e6be7a288a6cc17a44486afd546fe4a97b588e9f2deaff9318
    Image:         k8s.gcr.io/sig-storage/csi-provisioner:v3.4.0
    Image ID:      k8s.gcr.io/sig-storage/csi-provisioner@sha256:7f0d080e35ac455c52956e451b8d230c1eca1a8e0d943fdb657df4e093d03d0f
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --volume-name-prefix=csivol
      --volume-name-uuid-length=10
      --v=5
      --leader-election
      --default-fstype=ext4
      --extra-create-metadata
      --feature-gates=Topology=true
      --enable-capacity=true
      --capacity-ownerref-level=2
      --capacity-poll-interval=5m
    State:          Running
      Started:      Tue, 19 Sep 2023 10:14:09 +0900
    Ready:          True
    Restart Count:  1
    Environment:
      ADDRESS:    /var/run/csi/csi.sock
      NAMESPACE:  xxxnamespacexxx (v1:metadata.namespace)
      POD_NAME:   powerstore-controller-65856bff55-rgpq2 (v1:metadata.name)
    Mounts:
      /var/run/csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gq9zz (ro)
  snapshotter:
    Container ID:  cri-o://8817e6658cf62e81ec7fee3d5b62d9b444013ebff2a3fbcca096edbe33b8cce4
    Image:         k8s.gcr.io/sig-storage/csi-snapshotter:v6.2.1
    Image ID:      k8s.gcr.io/sig-storage/csi-snapshotter@sha256:2f4a5f6628f7359873bdbe99a26b33e4311e140c3e359306319e33f0cb3cde38
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --v=5
      --leader-election
      --snapshot-name-prefix=csisnap
    State:          Running
      Started:      Tue, 19 Sep 2023 10:14:23 +0900
    Ready:          True
    Restart Count:  1
    Environment:
      ADDRESS:  /var/run/csi/csi.sock
    Mounts:
      /var/run/csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gq9zz (ro)
  dell-csi-replicator:
    Container ID:  cri-o://46a1fc14ba1aac19f40b6ee80ec7ad5c1dd15dece5d1306a8e8e022c0d46f8e1
    Image:         dellemc/dell-csi-replicator:v1.4.0
    Image ID:      docker.io/dellemc/dell-csi-replicator@sha256:cea2d7a9a83f19fd5bfd0d289adfeafbe3b0dff01be8d2422e9618c937ae9f0a
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-address=$(ADDRESS)
      --leader-election=true
      --worker-threads=2
      --retry-interval-start=1s
      --retry-interval-max=300s
      --timeout=300s
      --context-prefix=powerstore
      --prefix=replication.storage.dell.com
    State:          Running
      Started:      Tue, 19 Sep 2023 10:14:33 +0900
    Ready:          True
    Restart Count:  1
    Environment:
      ADDRESS:                             /var/run/csi/csi.sock
      X_CSI_REPLICATION_CONFIG_DIR:        /powerstore-config-params
      X_CSI_REPLICATION_CONFIG_FILE_NAME:  driver-config-params.yaml
    Mounts:
      /powerstore-config-params from powerstore-config-params (rw)
      /var/run/csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gq9zz (ro)
  csi-metadata-retriever:
    Container ID:  cri-o://4a98a2d22111356fad0a89a4c957b254c38536cecfe4c2d838803193a5af1833
    Image:         dellemc/csi-metadata-retriever:v1.3.0
    Image ID:      docker.io/dellemc/csi-metadata-retriever@sha256:5496d773ec8e13d7289376d06211622eeec471e5e901531c4b0e784e926704b6
    Port:          <none>
    Host Port:     <none>
    Command:
      /csi-metadata-retriever
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 25 Sep 2023 09:52:52 +0900
      Finished:     Mon, 25 Sep 2023 09:52:52 +0900
    Ready:          False
    Restart Count:  1689
    Environment:
      CSI_RETRIEVER_ENDPOINT:  /var/run/csi/csi_retriever.sock
    Mounts:
      /var/run/csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gq9zz (ro)
  driver:
    Container ID:  cri-o://669594d7f5f797046e759de66532eba8312dc215bfcfa70beabb2a42f70b533f
    Image:         dellemc/csi-powerstore:v2.6.0
    Image ID:      docker.io/dellemc/csi-powerstore@sha256:b1d8112dc0467f1056b5a6fe698be3d8e7ff6f6e646c15e9bd758a6ad1ff8cff
    Port:          <none>
    Host Port:     <none>
    Command:
      /csi-powerstore
    State:          Running
      Started:      Tue, 19 Sep 2023 10:14:42 +0900
    Ready:          True
    Restart Count:  1
    Environment:
      CSI_ENDPOINT:                         /var/run/csi/csi.sock
      CSI_RETRIEVER_ENDPOINT:               /var/run/csi/csi_retriever.sock
      X_CSI_MODE:                           controller
      X_CSI_DRIVER_NAME:                    csi-powerstore.dellemc.com
      X_CSI_POWERSTORE_EXTERNAL_ACCESS:
      X_CSI_NFS_ACLS:                       0777
      X_CSI_POWERSTORE_CONFIG_PATH:         /powerstore-config/config
      X_CSI_POWERSTORE_CONFIG_PARAMS_PATH:  /powerstore-config-params/driver-config-params.yaml
      X_CSI_PODMON_ENABLED:                 false
      X_CSI_PODMON_API_PORT:                8083
      X_CSI_REPLICATION_CONTEXT_PREFIX:     powerstore
      X_CSI_REPLICATION_PREFIX:             replication.storage.dell.com
      GOPOWERSTORE_DEBUG:                   true
      CSI_AUTO_ROUND_OFF_FILESYSTEM_SIZE:   false
    Mounts:
      /powerstore-config from powerstore-config (rw)
      /powerstore-config-params from powerstore-config-params (rw)
      /var/run/csi from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gq9zz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  powerstore-config-params:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      powerstore-config-params
    Optional:  false
  powerstore-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  powerstore-config
    Optional:    false
  kube-api-access-gq9zz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   BestEffort
Node-Selectors:              node-role.kubernetes.io/infra=
Tolerations:                 node-role.kubernetes.io/infra:NoSchedule op=Exists
                             node-role.kubernetes.io/infra:NoExecute op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                      From     Message
  ----     ------   ----                     ----     -------
  Normal   Pulled   115m (x1666 over 5d23h)  kubelet  Container image "dellemc/csi-metadata-retriever:v1.3.0" already present on machine
  Warning  BackOff  41s (x39691 over 5d23h)  kubelet  Back-off restarting failed container
```

```
$ oc logs powerstore-controller-65856bff55-rgpq2 --tail=5
Defaulted container "attacher" out of: attacher, resizer, provisioner, snapshotter, dell-csi-replicator, csi-metadata-retriever, driver
W0925 04:52:25.317381       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0925 04:52:35.317740       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0925 04:52:45.317724       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0925 04:52:55.317717       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
W0925 04:53:05.317145       1 connection.go:183] Still connecting to unix:///var/run/csi/csi.sock
```

```
$ oc logs powerstore-controller-65856bff55-rgpq2 -c csi-metadata-retriever
time="2023-09-25T02:35:24Z" level=fatal msg="failed to listen" error="listen unix /var/run/csi/csi_retriever.sock: bind: address already in use"
```

**Comment by adarsh-dell** [comment] 2023-09-25 07:28
Hello @at-tkimura,

I've done some initial investigation, and here's what I found:

The problem you encountered, where it seems like the Unix socket is already binded, could be because a previous instance of the program didn't clean up properly because nodes were terminated unexpectedly.

Remember when you mentioned that "All nodes in the OCP cluster that were running the CSI driver terminated unexpectedly"? Well, in such cases, it's quite common for things to get a bit messy like this.

Considering these factors, It seems like the issue might have been caused by the unexpected shutdown of the nodes in your cluster. If you're okay with this, please let us know, and we'll go ahead and close the issue. Your feedback is important to us.

**Comment by at-tkimura** [comment] 2023-09-26 01:46
@adarsh-dell 
I understand the cause.
This issue has been resolved, so it can be closed.
Thank you for your support.

**Comment by adarsh-dell** [comment] 2023-09-26 08:15
Thank you @at-tkimura for the confirmation and for gathering all this data on our behalf. I will now proceed to close this GitHub issue based on the confirmation provided in your latest comment.

**Closed by adarsh-dell** 2023-09-26 08:15 UTC
Labels: type/question, area/csi-powerstore
